name = "tunaicukaimy"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"


[vars]
# Environment variables will be populated from the Cloudflare Dashboard
# VITE_SUPABASE_URL = "placeholder" 
